from api.blueprints.usuarios import usuario
from api.blueprints.index import index
from api.blueprints.empleados import empleado
from api.blueprints.clientes import cliente
from api.blueprints.vehiculos import vehiculo
from api.blueprints.inventarios import inventario
from api.blueprints.reparaciones import reparacion
from api.blueprints.garantias import garantia
from api.blueprints.reparacion_detalles import reparacion_detalle
from api.blueprints.tipos_usuario import tipo_usuario
from api.blueprints.partes import parte
from api.blueprints.tipos_parte import tipo_parte